import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

// icons
import { BsFillMoonStarsFill } from "react-icons/bs";
import { BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

// images
import devwave from "../public/dev-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Carlos Daniel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="bg-slate-100 dark:bg-slate-800 px-10 md:px-20 lg:px-40
        text-gray-800 dark:text-gray-300"
      >
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              developed by ruuuff
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    className="cursor-pointer text-2xl text-yellow-500"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                ) : (
                  <BsFillMoonStarsFill
                    className="cursor-pointer text-2xl text-slate-800"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                )}
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 
                  text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 max-w-7xl mx-auto">
            <h2
              className="text-5xl py-2 text-teal-600 dark:text-teal-500
              font-medium md:text-6xl"
            >
              Carlos Daniel
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer.
            </h3>
            <p className="text-md py-5 leading-8 max-w-lg mx-auto md:text-xl">
              Freelancer providing services for programming. Join me down below
              and let's get cracking!
            </p>
          </div>
          <div
            className="text-5xl flex justify-center gap-16 py-3
            text-gray-600 dark:text-gray-100"
          >
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div
            className="relative mx-auto bg-gradient-to-b from-teal-500
            rounded-full w-80 h-80 mt-20 overflow-hidden
            md:w-96 md:h-96"
          >
            <Image
              src={devwave}
              alt="Developer wave"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        <section className="max-w-7xl mx-auto">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 ">
              Since as beginning of my journey as a freelancer designer and
              developer. I've done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for{" "}
              <span className="text-teal-500">startups</span> and collaborated
              with talented people to create digital products for both business
              and consumer use
            </p>
            <p className="text-md py-2 leading-8 ">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="lg:flex lg:justify-center gap-10">
            {[design, code, consulting].map((image) => (
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-700">
                <Image src={image} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                  Beautiful Designs
                </h3>
                <p className="py-2 dark:text-gray-300">
                  Creating elegant designs suited for your needs following core
                  design theory.
                </p>
                <h4 className="py-4 text-teal-600">Design tools I use</h4>
                <p className=" py-1">Photoshop</p>
                <p className=" py-1">Illustrator</p>
                <p className=" py-1">Figma</p>
              </div>
            ))}
          </div>
        </section>
        <section className="max-w-7xl mx-auto">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 ">
              Since as beginning of my journey as a freelancer designer and
              developer. I've done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for{" "}
              <span className="text-teal-500">startups</span> and collaborated
              with talented people to create digital products for both business
              and consumer use
            </p>
            <p className="text-md py-2 leading-8 ">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="grid grid-cols-1 gap-10 py-10 lg:grid-cols-2">
            {[web1, web2, web3, web4, web5, web6].map((image) => (
              <div className="basis-1/3 flex-1">
                <Image
                  src={image}
                  className="rounded-lg object-cover"
                  width="100%"
                  height="100%"
                  layout="responsive"
                />
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
